title: Steven Lawrence
description: Biostatistician / Data Scientist | Real-World Evidence | Health Equity
theme: jekyll-theme-minimal

show_downloads: false

url: "https://steven-lr.github.io"

plugins:
  - jekyll-seo-tag

