title: Steven Lawrence
description: Senior Biostatistician | Bayesian Modeling | Reproducible Analytics
theme: jekyll-theme-minimal

show_downloads: false

url: "https://steven-lr.github.io"

plugins:
  - jekyll-seo-tag

